version: '3.8'

services:
  backend_tsk:
    build: .
    ports:
      - "5001:5000"
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - MONGO_URI=${MONGO_URI}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - FLASK_ENV=${FLASK_ENV}
    depends_on:
      - mongo_tsk
      - redis_tsk

  mongo_tsk:
    image: mongo
    container_name: mongo_tsk
    ports:
      - "27018:27017"

  redis_tsk:
    image: redis
    container_name: redis_tsk
    ports:
      - "6379:6379"
